---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.espresso_shop_web.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.espresso_shop_web.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.espresso_shop_web.name }}
        version: v1
    spec:
      containers:
        - name: {{ .Values.espresso_shop_web.name }}
          image: "{{ .Values.espresso_shop_web.image.repository }}:{{ .Values.espresso_shop_web.image.tag }}"
          env:
            - name: {{ .Values.espresso_shop_web.env.name1 }}
              value: {{ .Values.espresso_shop_web.env.value1 }}
            - name: {{ .Values.espresso_shop_web.env.name2 }}
              value: {{ .Values.espresso_shop_web.env.value2 }}
            - name: {{ .Values.database.redis.env.name1 }}
              value: {{ .Values.database.redis.env.value1 }}
            - name: {{ .Values.database.redis.env.name2 }}
              value: {{ .Values.database.redis.env.value2 }}   
          imagePullPolicy: {{ .Values.espresso_shop_web.imagePullPolicy }}
          ports:
            - name: {{ .Values.espresso_shop_web.services.containerName }}
              containerPort: {{ .Values.espresso_shop_web.services.containerPort }}
              protocol: {{ .Values.espresso_shop_web.services.protocol }}
          resources:
             {{- toYaml .Values.espresso_shop_web.resources | nindent 12 }}
