---
# Source: {{ .Values.espresso_shop_reviews.name }}-v1/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.espresso_shop_reviews.name }}-v2
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.espresso_shop_reviews.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.espresso_shop_reviews.name }}
        version: v2
    spec:
      containers:
      - name: {{ .Values.espresso_shop_reviews.name }}
        image: "{{ .Values.espresso_shop_reviews.image.repository }}:{{ .Values.espresso_shop_reviews.image.tag }}"
        imagePullPolicy: {{ .Values.espresso_shop_reviews.imagePullPolicy }}
        env:
          - name: {{ .Values.espresso_shop_reviews.env.name1 }}
            value: {{ .Values.espresso_shop_reviews.env.value1 }}
          - name: {{ .Values.espresso_shop_reviews.env.name2 }}
            value: {{ .Values.espresso_shop_reviews.env.value2 }}
          - name: {{ .Values.espresso_shop_reviews.env.name3 }}
            value: {{ .Values.espresso_shop_reviews.env.value3 }}
          - name: {{ .Values.espresso_shop_reviews.env.name4 }}
            value: {{ .Values.espresso_shop_reviews.env.value4 }}
          - name: {{ .Values.espresso_shop_reviews.env.name5 }}
            value: {{ .Values.espresso_shop_reviews.env.value6 }}
        ports:
          - name: {{ .Values.espresso_shop_reviews.services.containerName }}
            containerPort: {{ .Values.espresso_shop_reviews.services.containerPort }}
            protocol: {{ .Values.espresso_shop_reviews.services.protocol }}
        resources:
           {{- toYaml .Values.espresso_shop_reviews.resources | nindent 12 }}
