apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.database.postgres.name }}-replication
spec:
  minAvailable: {{ .Values.PodDisruptionBudget }}
  selector:
    matchLabels:
      app: {{ .Values.database.postgres.name }}-replication
