apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.espresso_shop_reviews.name }}-v2
spec:
  minAvailable: {{ .Values.PodDisruptionBudget }}
  selector:
    matchLabels:
      app: {{ .Values.espresso_shop_reviews.name }}-v2

