---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.espresso_shop_reviews.name }}-svc
  labels:
    app: {{ .Values.espresso_shop_reviews.name }}
    version: {{ .Values.espresso_shop_reviews.env.value5 }}
    version: {{ .Values.espresso_shop_reviews.env.value6 }}
spec:
  type: {{ .Values.espresso_shop_reviews.services.type }}
  ports:
    - port: {{ .Values.espresso_shop_reviews.services.port }}
      targetPort: {{ .Values.espresso_shop_reviews.services.containerPort }}
      protocol: {{ .Values.espresso_shop_reviews.services.protocol }}
      name: {{ .Values.espresso_shop_reviews.services.containerName }}
  selector:
    app: {{ .Values.espresso_shop_reviews.name }}


