---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.postgres.name }}-replication
  labels:
    app: {{ .Values.espresso_shop_reviews.name }}
spec:
  type: {{ .Values.database.postgres.service.type }} 
  ports:
    - port: {{ .Values.database.postgres.service.ports.containerPort }} 
  selector:
    app: {{ .Values.espresso_shop_reviews.name }}

