---
apiVersion: v1
kind: Service                    
metadata:
  name: {{ .Values.database.redis.name }} 
  labels:
    app: {{ .Values.espresso_shop_web.name }}
spec:
  type: {{ .Values.database.redis.service.type }}             
  ports:                         
  - name: {{ .Values.database.redis.service.name }}
    port: {{ .Values.database.redis.service.ports.port }}
    targetPort: {{ .Values.database.redis.service.ports.containerPort }}
  selector:
    app: {{ .Values.espresso_shop_web.name }}

