---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.espresso_shop_web.name }}-svc
  labels:
    app: {{ .Values.espresso_shop_web.name }}
spec:
  type: {{ .Values.espresso_shop_web.services.type }}
  ports:
    - port: {{ .Values.espresso_shop_web.services.port }}
      targetPort: {{ .Values.espresso_shop_web.services.containerPort }}
      protocol: {{ .Values.espresso_shop_web.services.protocol }}
      name: {{ .Values.espresso_shop_web.services.containerName }}
  selector:
    app: {{ .Values.espresso_shop_web.name }}

